apiVersion: v1
kind: ConfigMap
metadata:
  name: nbody-script
data:
  run-nbody.sh: |
    #!/bin/bash
    set -e
    apt-get update && apt-get install -y xvfb
    (Xvfb :1 &)
    export DISPLAY=:1
    /cuda-samples/sample "$@"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: nbody
spec:
  template:
    spec:
      restartPolicy: OnFailure
      hostIPC: true
      containers:
      - image: nvcr.io/nvidia/k8s/cuda-sample:nbody
        name: nbody
        command: ["/run-nbody.sh"]
        args: ["nbody", "-benchmark", "-numbodies=256000"]
        resources:
          limits:
            nvidia.com/gpu: 0
        env:
        - name: CUDA_MPS_PIPE_DIRECTORY
          value: /tmp/nvidia-mps
        - name: CUDA_MPS_ENABLE_PER_CTX_DEVICE_MULTIPROCESSOR_PARTITIONING
          value: "1"
        - name: CUDA_MPS_ACTIVE_THREAD_PERCENTAGE
          value: "20"
        volumeMounts:
        - name: nvidia-mps
          mountPath: /tmp/nvidia-mps
        - name: script-volume
          mountPath: /run-nbody.sh
          subPath: run-nbody.sh
      volumes:
      - name: nvidia-mps
        hostPath:
          path: /tmp/nvidia-mps
      - name: script-volume
        configMap:
          name: nbody-script
          defaultMode: 0777
